# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170918_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-date_created'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
