# Generated by Django 2.0.2 on 2018-04-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='full_name',
        ),
    ]
